services:
  hytale:
    container_name: hytale-server
    build: .
    restart: unless-stopped

    ports:
      - "25665:25565/tcp"
      - "25665:25565/udp"

    volumes:
      - ./server:/hytale-data

    environment:
      TZ: Europe/Berlin
