services:
  hytale:
    container_name: hytale-server
    build: .
    restart: unless-stopped

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"

    volumes:
      - ./server:/hytale

    environment:
      TZ: Europe/Berlin