services:
  hytale:
    container_name: hytale-server
    build: .
    restart: unless-stopped

    ports:
      - "5520:5520/udp"

    volumes:
      - ./server:/hytale-data

    environment:
      TZ: Europe/Berlin
